# Jekyll configuration

theme: jekyll-theme-leap-day

destination:  "./jekyll/site"
layouts_dir:  "./jekyll/layouts"
includes_dir: "./jekyll/includes"
data_dir:     "./jekyll/data"
plugins_dir:  "./jekyll/plugins"

baseurl: "/documents"

title: Chun-Ge Documents
description: May the power of CHUN be with you.

encoding: "utf-8"

highlighter: rouge
markdown: kramdown

exclude: ["Gemfile*", "LICENSE", "*.bak", ".gitignore"]
